In [9]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])

print(i[0])

10


In [3]:
i =np.array([10,20,30,40,50,60,70,80])

print(i[3:6])

[40 50 60]


In [4]:
i =np.array([10,20,30,40,50,60,70,80,])

print(i[2:])

[30 40 50 60 70 80]


In [7]:
import numpy as np

i = np.array([
[10, 20, 30],
[40, 50, 60]
])

print(i)

[[10 20 30]
 [40 50 60]]


In [8]:
import numpy as np
i = np.array([
[[10, 20, 30], [40, 50, 60]],
[[11, 22, 33], [44, 55, 66]]
])
print(i)

[[[10 20 30]
  [40 50 60]]

 [[11 22 33]
  [44 55 66]]]


In [10]:
import numpy as np

i = np.array([
[10,20,30,40,50],
[60,70,80,90,100]
])

print(i[1, 1])

70


In [11]:
import numpy as np

i = np.array([
[10,20,30,40,50],
[60,70,80,90,100]
])

print(i[0, 4])

50


In [15]:
i= np.array([
[[10, 20, 30], [40, 50, 60]], # 0 - 0 1 - 0 1 2
[[70, 80, 90], [100, 110, 120]] # 1 - 0 1 - 0 1 2
])

print(i[0, 1, 2])

60


In [20]:
arr = np.array([
[[10, 20, 30], [40, 50, 60]], # 0 - 0 1 - 0 1 2
[[70, 80, 90], [100, 110, 120]] # 1 - 0 1 - 0 1 2
])

print(arr[1, 1, 2])

120


In [21]:
arr = np.array([
[[10, 20, 30], [40, 50, 60]], # 0 - 0 1 - 0 1 2
[[70, 80, 90], [100, 110, 120]] # 1 - 0 1 - 0 1 2
])

print(arr[1, 1, -1])

120


In [23]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60])

print(i[-1])

60
